blog_project/blog_app/urls.py
from django.urls import path

from . import views

app_name = 'blog_app'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('post/<slug:post_slug>', views.post_detail, name="post_detail"),
    path("results/", views.search_post, name="search")
]

blog_project/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls')),
]

blog_project/blog_app/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    thumbnail = models.ImageField(upload_to = "static/images", null=True, blank=True)
    slug = models.SlugField()
    title = models.CharField(max_length=100)
    content = models.TextField()
    categories = models.ForeignKey('Category', on_delete=models.CASCADE)
    data_criacao = models.DateTimeField(auto_now_add=True)
    publicacao = models.DateTimeField()

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=120)
    slug = models.SlugField()

    def __str__(self):
        return self.name

blog_project/blog_app/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .models import Post, Category


# Create your views here.

def blog(request):

    list_posts = Post.objects.order_by('-publicacao')
    paginator = Paginator(list_posts, 3)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, "blog_app/blog.html", {'list_post':list_posts, 'page_obj': page_obj, "search_post": search_post})

def post_detail(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    return render(request, "blog_app/post_detail.html", {"post":post })

def search_post(request):
  query = request.GET.get('q')
  posts = Post.objects.filter(
      Q(title__icontains=query) |
      Q(content__icontains=query) |
      Q(categories__name__icontains=query)
      )
  return render(request, 'blog_app/search.html', {'posts': posts})

blog_project/blog_app/templates/blog_app/blog.html
{% extends 'blog_app/index.html' %}
{% block content %}
  <section class="jumbotron text-center">
    <div class="container">
      <h1>Todos os posts</h1>
      <p class="lead text-muted">Abaixo todos os posts já postados:</p>
    </div>
  </section>
    <div class="container">
        <div class="row">
        {% for post in page_obj %}
            <div class="col-4 py-3">
                <div class="col mb-4">
                    <div class="card h-100">
                        <a href="{% url 'blog_app:post_detail' post.slug %}">
                            <img src="{{post.thumbnail}}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-text">{{post.content|slice:":25"}}...</p>
                                <p class="card-text"><small class="text-muted">{{post.publicacao}}</small></p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="pagination justify-content-center   ">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; Primeira</a>
                <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
            {% endif %}

            <span class="current">
                Pág {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Próxima</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

blog_project/blog_app/templates/blog_app/index.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Teste Blog</title>
    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>
  <body>
<header>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
        <a href="{% url 'blog_app:blog' %}" class="navbar-brand d-flex align-items-center">
            <strong><img src="{% static 'svg/book-solid.svg' %}" class="icon_arrow invert_color">Blog</strong>
        </a>
        <form action="{% url 'blog_app:search' %}" method="GET" id="form1">
            <div class="input-group" style="padding-top: 6%;">
                <input name="q" value="{{request.GET.q}}" type="text" class="form-control" placeholder="Buscar Post" aria-label="Buscar Post" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <a href="#" onclick="document.getElementById('form1').submit();"><span class="input-group-text" id="basic-addon2"><img src="{% static 'svg/search-solid.svg' %}" style="height: 23px;"></span></a>
                </div>
            </div>
        </form>
    </div>
  </div>
</header>

<main role="main">
    {% block content %}
    {% endblock %}
</main>

<footer class="text-muted">
  <div class="container">
    <p class="text-center">
      <a href="#"><img src="{% static 'svg/arrow_up.svg' %}" class="icon_arrow" >Voltar para o topo </a>
    </p>
  </div>
</footer>

blog_project/blog_app/templates/blog_app/post_detail.html
{% extends "blog_app/index.html" %}
{% block content %}
{% load static %}
  <div class="container text-center">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="mt-4">{{post.title}}</h1>
        <hr>
        <p>Postado em {{post.publicacao}}</p>
        <hr>
        <img class="img-fluid rounded" src="/{{post.thumbnail}}" alt="">
        <hr>
        <p class="lead text-justify">{{post.content}}</p>
        <hr>
      </div>
    </div>
  </div>
{% endblock %}

blog_project/blog_app/templates/blog_app/search.html
{% extends 'blog_app/index.html' %}
{% block content %}
 <section class="jumbotron text-center">
    <div class="container">
      <h1>Resultado da pesquisa</h1>
    </div>
  </section>
<div class="container">
    <div class="row">
    {% if posts %}
    {% for post in posts %}
        <div class="col-4 py-3">
            <div class="col mb-4">
                <div class="card h-100">
                    <a href="{% url 'blog_app:post_detail' post.slug %}">
                        <img src="/{{post.thumbnail}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{post.title}}</h5>
                            <p class="card-text">{{post.content|slice:":25"}}...</p>
                            <p class="card-text"><small class="text-muted">{{post.publicacao}}</small></p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
  {% endfor %}
  </div>
{% else %}
<h3>Nenhum post encontrado!</h3>
{% endif %}
</div>

{% endblock %}